#!/usr/bin/env ruby

require 'net/ssh'
require 'trollop'
require 'peach'
require 'json'

# Credentials are put here, instead of CLI options, so that
# the password doesn't show up when you run 'ps'
user = 'user'
password = 'password'

# CLI help menu
opts = Trollop::options do
  opt :command, 'Command to run', :required => true, :type => String
  opt :file, 'Hosts list file', :required => true, :type => String
  opt :verbose, 'Verbose mode'
end

hosts = []
File.open(opts.file).each_line { |l| hosts << l.gsub("\n", '') }

# multithreaded command execution
results = {}
hosts.peach do |host|
  begin
    Net::SSH.start(host, user, :password => password) do |ssh|
      output = []
      ssh.exec!(opts.command).each_line do |out|
        output << out.gsub("\n", '')
      end
      results[host] = output
    end
  rescue => e
    puts host + ': ' + e.to_s
  end
end
if opts.verbose
  puts JSON.pretty_generate(results)
end
